name: Continuous Integration

on:
  push:
  workflow_dispatch:

jobs:
  execute_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Appium
        run: |
          npm install -g appium
          appium --version

      - name: Install UiAutomator2
        run: |
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          nohup appium -p 4723 --base-path /wd/hub > appium.log 2>&1 &

      - name: Install Android SDK system image
        run: |
          sdkmanager --install "system-images;android-34;google_apis;x86_64"
          sdkmanager --licenses

      - name: Create Android Virtual Device (AVD)
        run: |
          echo no | avdmanager create avd -n "Pixel_7_Pro_API_34" -k "system-images;android-34;google_apis;x86_64" -d pixel_7_pro
          avdmanager list avd

      - name: Configure KVM
        run: |
          sudo usermod -aG kvm $USER
          sudo chmod 666 /dev/kvm

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_6_pro
          script: |
            adb devices
            robot -d ./reports -v APPIUM_PORT:4723 .

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: reports

      - name: Upload Appium Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: appium-logs
          path: appium.log
