name: Run Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-appiumlibrary
          
    - name: Install Appium
      run: |
        npm install -g appium

    - name: Install Appium UIAutomator2 Driver
      run: |     
        npx appium driver install uiautomator2

    - name: Add adb to PATH
      run: |
        export PATH=$PATH:/usr/local/lib/android/sdk/platform-tools
  
    - name: Start Appium Server
      run: |
        appium --port 4723 &  

    - name: Run Robot Framework Tests
      run: |
        mkdir -p appium-expandtesting_UI/results        
        robot -d ./results tests